global using Xunit;
global using Moq;
global using ParsaLibraryManagement.Application.DTOs;
global using ParsaLibraryManagement.Domain.Entities;
global using ParsaLibraryManagement.Domain.Common;
global using ParsaLibraryManagement.Domain.Models;
global using ParsaLibraryManagement.Domain.Interfaces.Repository;
global using ParsaLibraryManagement.Application.Services;
global using Test.ParsaLibraryManagement.UnitTests.Application.Services.Base;
